# Server Port
server:
  port: 8081

# Spring Application Details
spring:
  application:
    name: order-service
  # Spring cloud streams
  cloud:
    stream:
      bindings:
        input:
          destination: channel-stream
  # Enabling H2 Console
  h2:
    console:
      enabled: true
  # H2 DataBase details
  datasource:
    url: jdbc:h2:mem:${spring.application.name}db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  # Zipkin info
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1

# Logging info
logging:
  file:
    path: .
  name: ${spring.application.name}.log
  level:
    com:
      wysoft: DEBUG

destination:
  host: localhost
  port: 5044
