# Server port
server:
  port: 8027

# Spring Application Details
spring:
  application:
    name: orchestrator
  # Spring cloud streams
  cloud:
    stream:
      bindings:
        output:
          destination: channel-stream
  # Enabling H2 Console
  h2:
    console:
      enabled: true
  # H2 DataBase details
  datasource:
    url: 'jdbc:h2:mem:${spring.application.name}db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  # Zipkin info
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
# Service URL's
order:
  service:
    url: http://localhost:8081/orders/

customer:
  service:
    url: http://localhost:8082/customers/

# Logstash
logstash:
  server:
    host: localhost
    port: 5000

# Logging info
logging:
  file:
    path: ./log
#  name: ${spring.application.name}.log
  level:
    com:
      wysoft: DEBUG